INSERT INTO "DataManager_country"(name, forms) VALUES('Adria Airways', 'Adria Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('Aegean Airlines', 'Aegean Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Aer Lingus', 'Aer Lingus');
INSERT INTO "DataManager_country"(name, forms) VALUES('Aeroflot', 'Aeroflot');
INSERT INTO "DataManager_country"(name, forms) VALUES('Aerolineas Argentinas', 'Aerolineas Argentinas');
INSERT INTO "DataManager_country"(name, forms) VALUES('Aeromexico', 'Aeromexico');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air Cairo', 'Air Cairo');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air Canada', 'Air Canada');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air China', 'Air China');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air Contractors', 'Air Contractors');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air Europa', 'Air Europa');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air France', 'Air France');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air India', 'Air India');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air India Express', 'Air India Express, Air India');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air Memphis', 'Air Memphis');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air New Zealand', 'Air New Zealand');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air One', 'Air One');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air Royal Maroc', 'Air Royal Maroc');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air Serbia', 'Air Serbia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air Tahiti Nui', 'Air Tahiti Nui');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air Transat', 'Air Transat');
INSERT INTO "DataManager_country"(name, forms) VALUES('Air Vanuatu', 'Air Vanuatu');
INSERT INTO "DataManager_country"(name, forms) VALUES('AirAsia', 'AirAsia');
INSERT INTO "DataManager_country"(name, forms) VALUES('AirAsia X', 'AirAsia X');
INSERT INTO "DataManager_country"(name, forms) VALUES('AirBaltic', 'AirBaltic');
INSERT INTO "DataManager_country"(name, forms) VALUES('airberlin', 'airberlin');
INSERT INTO "DataManager_country"(name, forms) VALUES('Alaska airlines', 'Alaska airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Alitalia', 'Alitalia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Allegiant', 'Allegiant');
INSERT INTO "DataManager_country"(name, forms) VALUES('American airlines', 'American airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('ANA', 'ANA');
INSERT INTO "DataManager_country"(name, forms) VALUES('Arkia', 'Arkia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Asiana', 'Asiana');
INSERT INTO "DataManager_country"(name, forms) VALUES('Atlantic Airlines', 'Atlantic Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('AtlasGlobal', 'AtlasGlobal');
INSERT INTO "DataManager_country"(name, forms) VALUES('Austrian', 'Austrian, Austrian Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Avianca', 'Avianca');
INSERT INTO "DataManager_country"(name, forms) VALUES('Balkan Holidays', 'Balkan Holidays');
INSERT INTO "DataManager_country"(name, forms) VALUES('Bangkok Airways', 'Bangkok Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('Belavia', 'Belavia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Bingo Airways', 'Bingo Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('British Airways', 'British Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('Brussels airlines', 'Brussels airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Bulgaria Air', 'Bulgaria Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('Carpatair', 'Carpatair');
INSERT INTO "DataManager_country"(name, forms) VALUES('Cathay Pacific', 'Cathay Pacific');
INSERT INTO "DataManager_country"(name, forms) VALUES('CEBU Pacific Air', 'CEBU Pacific Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('China airlines', 'China airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('China Eastern', 'China Eastern');
INSERT INTO "DataManager_country"(name, forms) VALUES('China Southern', 'China Southern');
INSERT INTO "DataManager_country"(name, forms) VALUES('Condor', 'Condor');
INSERT INTO "DataManager_country"(name, forms) VALUES('Copa airlines', 'Copa airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Corendon', 'Corendon, Cordendon Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Czech airlines', 'Czech airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Delta', 'Delta');
INSERT INTO "DataManager_country"(name, forms) VALUES('Dragonair', 'Dragonair');
INSERT INTO "DataManager_country"(name, forms) VALUES('easyJet', 'easyJet');
INSERT INTO "DataManager_country"(name, forms) VALUES('EL AL', 'EL AL');
INSERT INTO "DataManager_country"(name, forms) VALUES('Enter Air', 'Enter Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('Emirates', 'Emirates, Emirates airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Ethiopian airlines', 'Ethiopian airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Etihad', 'Etihad');
INSERT INTO "DataManager_country"(name, forms) VALUES('Eurolot', 'Eurolot');
INSERT INTO "DataManager_country"(name, forms) VALUES('EVA Air', 'EVA Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('Farnair Europe', 'Farnair Europe');
INSERT INTO "DataManager_country"(name, forms) VALUES('Fiji Airways', 'Fiji Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('Finnair', 'Finnair');
INSERT INTO "DataManager_country"(name, forms) VALUES('Flybe', 'Flybe');
INSERT INTO "DataManager_country"(name, forms) VALUES('Free Bird Airlines', 'Free Bird Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Frontier', 'Frontier');
INSERT INTO "DataManager_country"(name, forms) VALUES('Garuda Indonesia', 'Garuda Indonesia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Germanwings', 'Germanwings');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gol', 'Gol');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gulf Air', 'Gulf Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('Hainan airlines', 'Hainan airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Hawaiian airlines', 'Hawaiian airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Iberia', 'Iberia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Icelandair', 'Icelandair');
INSERT INTO "DataManager_country"(name, forms) VALUES('Iceland Express', 'Iceland Express');
INSERT INTO "DataManager_country"(name, forms) VALUES('IndiGo airlines', 'IndiGo airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Israir Airlines', 'Israir Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Japan airlines', 'Japan airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Jet Airways', 'Jet Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('Jet2', 'Jet2');
INSERT INTO "DataManager_country"(name, forms) VALUES('JetBlue', 'JetBlue');
INSERT INTO "DataManager_country"(name, forms) VALUES('Jetstar', 'Jetstar');
INSERT INTO "DataManager_country"(name, forms) VALUES('Karthago Airlines', 'Karthago Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kenya Airways', 'Kenya Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('KLM', 'KLM');
INSERT INTO "DataManager_country"(name, forms) VALUES('Korean Air', 'Korean Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('LAN airlines', 'LAN airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Lion airlines', 'Lion airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('LOT', 'Polskie Linie Lotnicze LOT, LOT, PLL LOT');
INSERT INTO "DataManager_country"(name, forms) VALUES('Lufthansa', 'Lufthansa');
INSERT INTO "DataManager_country"(name, forms) VALUES('Malaysia airlines', 'Malaysia airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('MNG Airlines', 'MNG Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Monarch', 'Monarch');
INSERT INTO "DataManager_country"(name, forms) VALUES('Nesma Airlines', 'Nesma Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Nok Air', 'Nok Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('Norwegian', 'Norwegian');
INSERT INTO "DataManager_country"(name, forms) VALUES('Nouvelair', 'Nouvelair');
INSERT INTO "DataManager_country"(name, forms) VALUES('Oman Air', 'Oman Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('Onur Air', 'Onur Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('OpenSkies', 'OpenSkies');
INSERT INTO "DataManager_country"(name, forms) VALUES('Quatar', 'Quatar,Quatar Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('Peach', 'Peach');
INSERT INTO "DataManager_country"(name, forms) VALUES('Pegasus Airlines', 'Pegasus Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Philippine airlines', 'Philippine airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Porter', 'Porter');
INSERT INTO "DataManager_country"(name, forms) VALUES('Qantas', 'Qantas');
INSERT INTO "DataManager_country"(name, forms) VALUES('Qatar Airways', 'Qatar Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('Regional Express', 'Regional Express');
INSERT INTO "DataManager_country"(name, forms) VALUES('Royal Brunei', 'Royal Brunei');
INSERT INTO "DataManager_country"(name, forms) VALUES('Royal Jordanian', 'Royal Jordanian');
INSERT INTO "DataManager_country"(name, forms) VALUES('Ryanair', 'Ryanair');
INSERT INTO "DataManager_country"(name, forms) VALUES('S7 airlines', 'S7 airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Saga Airlines', 'Saga Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('SAS', 'SAS, SAS Scandinavian Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Saudia', 'Saudia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Scoot airlines', 'Scoot "DataManager_country", Scoot');
INSERT INTO "DataManager_country"(name, forms) VALUES('Singapore airlines', 'Singapore airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Sky Airlines', 'Sky Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Skylanes', 'Skylanes');
INSERT INTO "DataManager_country"(name, forms) VALUES('Small Planet Airlines', 'Small Planet Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('South African Airways', 'South African Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('Southwest', 'Southwest');
INSERT INTO "DataManager_country"(name, forms) VALUES('SpiceJet', 'SpiceJet');
INSERT INTO "DataManager_country"(name, forms) VALUES('Spirit', 'Spirit');
INSERT INTO "DataManager_country"(name, forms) VALUES('Spring airlines', 'Spring airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Spring Japan', 'Spring Japan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Sprint Air', 'Sprint Air, SprintAir');
INSERT INTO "DataManager_country"(name, forms) VALUES('SriLankan airlines', 'SriLankan airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Sun d''Or International Airlines', 'Sun d''Or International Airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Sunexpress', 'Sunexpress');
INSERT INTO "DataManager_country"(name, forms) VALUES('Sun Country', 'Sun Country');
INSERT INTO "DataManager_country"(name, forms) VALUES('SWISS', 'SWISS, Swiss International');
INSERT INTO "DataManager_country"(name, forms) VALUES('TACA', 'TACA');
INSERT INTO "DataManager_country"(name, forms) VALUES('TAM', 'TAM');
INSERT INTO "DataManager_country"(name, forms) VALUES('TAP Portugal', 'TAP Portugal');
INSERT INTO "DataManager_country"(name, forms) VALUES('THAI', 'THAI');
INSERT INTO "DataManager_country"(name, forms) VALUES('Thomas Cook airlines', 'Thomas Cook airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Thomson', 'Thomson');
INSERT INTO "DataManager_country"(name, forms) VALUES('tigerair', 'tigerair');
INSERT INTO "DataManager_country"(name, forms) VALUES('Travel Service', 'Travel Service');
INSERT INTO "DataManager_country"(name, forms) VALUES('TUIfly', 'TUIfly');
INSERT INTO "DataManager_country"(name, forms) VALUES('Tunis Air', 'Tunis Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('Turkish airlines', 'Turkish airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Ukraine International', 'Ukraine International');
INSERT INTO "DataManager_country"(name, forms) VALUES('United', 'United');
INSERT INTO "DataManager_country"(name, forms) VALUES('US Airways', 'US Airways');
INSERT INTO "DataManager_country"(name, forms) VALUES('Vanilla Air', 'Vanilla Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('Virgin America', 'Virgin America');
INSERT INTO "DataManager_country"(name, forms) VALUES('Virgin Atlantic', 'Virgin Atlantic');
INSERT INTO "DataManager_country"(name, forms) VALUES('Virgin Australia', 'Virgin Australia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Volaris', 'Volaris');
INSERT INTO "DataManager_country"(name, forms) VALUES('Vueling airlines', 'Vueling airlines');
INSERT INTO "DataManager_country"(name, forms) VALUES('WestJet', 'WestJet');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wizzair', 'Wizzair, Wizz Air');
INSERT INTO "DataManager_country"(name, forms) VALUES('WizzAir Ukraina', 'WizzAir Ukraina');
INSERT INTO "DataManager_country"(name, forms) VALUES('WOW air', 'WOW air');