INSERT INTO "DataManager_country"(name, forms) VALUES('Abchazja', 'Abchazja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Afganistan', 'Afganistan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Albania', 'Albania');
INSERT INTO "DataManager_country"(name, forms) VALUES('Algieria', 'Algieria');
INSERT INTO "DataManager_country"(name, forms) VALUES('Andora', 'Andora');
INSERT INTO "DataManager_country"(name, forms) VALUES('Angola', 'Angola');
INSERT INTO "DataManager_country"(name, forms) VALUES('Antigua i Barbuda', 'Antigua i Barbuda');
INSERT INTO "DataManager_country"(name, forms) VALUES('Arabia Saudyjska', 'Arabia Saudyjska');
INSERT INTO "DataManager_country"(name, forms) VALUES('Argentyna', 'Argentyna');
INSERT INTO "DataManager_country"(name, forms) VALUES('Armenia', 'Armenia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Australia', 'Australia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Austria', 'Austria');
INSERT INTO "DataManager_country"(name, forms) VALUES('Azerbejdżan', 'Azerbejdżan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Bahamy', 'Bahamy');
INSERT INTO "DataManager_country"(name, forms) VALUES('Bahrajn', 'Bahrajn');
INSERT INTO "DataManager_country"(name, forms) VALUES('Bangladesz', 'Bangladesz');
INSERT INTO "DataManager_country"(name, forms) VALUES('Barbados', 'Barbados');
INSERT INTO "DataManager_country"(name, forms) VALUES('Belgia', 'Belgia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Belize', 'Belize');
INSERT INTO "DataManager_country"(name, forms) VALUES('Benin', 'Benin');
INSERT INTO "DataManager_country"(name, forms) VALUES('Bhutan', 'Bhutan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Białoruś', 'Białoruś');
INSERT INTO "DataManager_country"(name, forms) VALUES('Birma', 'Birma');
INSERT INTO "DataManager_country"(name, forms) VALUES('Boliwia', 'Boliwia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Bośnia i Hercegowina', 'Bośnia i Hercegowina');
INSERT INTO "DataManager_country"(name, forms) VALUES('Botswana', 'Botswana');
INSERT INTO "DataManager_country"(name, forms) VALUES('Brazylia', 'Brazylia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Brunei', 'Brunei');
INSERT INTO "DataManager_country"(name, forms) VALUES('Bułgaria', 'Bułgaria');
INSERT INTO "DataManager_country"(name, forms) VALUES('Burkina Faso', 'Burkina Faso');
INSERT INTO "DataManager_country"(name, forms) VALUES('Burundi', 'Burundi');
INSERT INTO "DataManager_country"(name, forms) VALUES('Chile', 'Chile');
INSERT INTO "DataManager_country"(name, forms) VALUES('Chiny', 'Chiny');
INSERT INTO "DataManager_country"(name, forms) VALUES('Chorwacja', 'Chorwacja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Cypr', 'Cypr');
INSERT INTO "DataManager_country"(name, forms) VALUES('Cypr Północny', 'Cypr Północny');
INSERT INTO "DataManager_country"(name, forms) VALUES('Czad', 'Czad');
INSERT INTO "DataManager_country"(name, forms) VALUES('Czarnogóra', 'Czarnogóra');
INSERT INTO "DataManager_country"(name, forms) VALUES('Czechy', 'Czechy,Republika Czeska');
INSERT INTO "DataManager_country"(name, forms) VALUES('Dania', 'Dania');
INSERT INTO "DataManager_country"(name, forms) VALUES('Demokratyczna Republika Konga', 'Demokratyczna Republika Konga');
INSERT INTO "DataManager_country"(name, forms) VALUES('Dominika', 'Dominika');
INSERT INTO "DataManager_country"(name, forms) VALUES('Dominikana', 'Dominikana,Republika Dominikańska');
INSERT INTO "DataManager_country"(name, forms) VALUES('Dżibuti', 'Dżibuti');
INSERT INTO "DataManager_country"(name, forms) VALUES('Egipt', 'Egipt');
INSERT INTO "DataManager_country"(name, forms) VALUES('Ekwador', 'Ekwador');
INSERT INTO "DataManager_country"(name, forms) VALUES('Erytrea', 'Erytrea');
INSERT INTO "DataManager_country"(name, forms) VALUES('Estonia', 'Estonia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Etiopia', 'Etiopia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Fidżi', 'Fidżi');
INSERT INTO "DataManager_country"(name, forms) VALUES('Filipiny', 'Filipiny');
INSERT INTO "DataManager_country"(name, forms) VALUES('Finlandia', 'Finlandia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Francja', 'Francja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gabon', 'Gabon');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gambia', 'Gambia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Ghana', 'Ghana');
INSERT INTO "DataManager_country"(name, forms) VALUES('Górski Karabach', 'Górski Karabach');
INSERT INTO "DataManager_country"(name, forms) VALUES('Grecja', 'Grecja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Grenada', 'Grenada');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gruzja', 'Gruzja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gujana', 'Gujana');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gwatemala', 'Gwatemala');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gwinea', 'Gwinea');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gwinea Bissau', 'Gwinea Bissau');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gwinea Równikowa', 'Gwinea Równikowa');
INSERT INTO "DataManager_country"(name, forms) VALUES('Haiti', 'Haiti');
INSERT INTO "DataManager_country"(name, forms) VALUES('Hiszpania', 'Hiszpania');
INSERT INTO "DataManager_country"(name, forms) VALUES('Holandia', 'Holandia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Honduras', 'Honduras');
INSERT INTO "DataManager_country"(name, forms) VALUES('Indie', 'Indie');
INSERT INTO "DataManager_country"(name, forms) VALUES('Indonezja', 'Indonezja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Irak', 'Irak');
INSERT INTO "DataManager_country"(name, forms) VALUES('Iran', 'Iran');
INSERT INTO "DataManager_country"(name, forms) VALUES('Irlandia', 'Irlandia,Irlandii');
INSERT INTO "DataManager_country"(name, forms) VALUES('Islandia', 'Islandia,Islandii');
INSERT INTO "DataManager_country"(name, forms) VALUES('Izrael', 'Izrael');
INSERT INTO "DataManager_country"(name, forms) VALUES('Jamajka', 'Jamajka');
INSERT INTO "DataManager_country"(name, forms) VALUES('Japonia', 'Japonia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Jemen', 'Jemen');
INSERT INTO "DataManager_country"(name, forms) VALUES('Jordania', 'Jordania');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kambodża', 'Kambodża');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kamerun', 'Kamerun');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kanada', 'Kanada');
INSERT INTO "DataManager_country"(name, forms) VALUES('Katar', 'Katar');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kazachstan', 'Kazachstan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kenia', 'Kenia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kirgistan', 'Kirgistan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kiribati', 'Kiribati');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kolumbia', 'Kolumbia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Komory', 'Komory');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kongo', 'Kongo');
INSERT INTO "DataManager_country"(name, forms) VALUES('Korea Południowa', 'Korea Południowa');
INSERT INTO "DataManager_country"(name, forms) VALUES('Korea Północna', 'Korea Północna');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kosowo', 'Kosowo');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kostaryka', 'Kostaryka');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kuba', 'Kuba');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kuwejt', 'Kuwejt');
INSERT INTO "DataManager_country"(name, forms) VALUES('Laos', 'Laos');
INSERT INTO "DataManager_country"(name, forms) VALUES('Lesotho', 'Lesotho');
INSERT INTO "DataManager_country"(name, forms) VALUES('Liban', 'Liban');
INSERT INTO "DataManager_country"(name, forms) VALUES('Liberia', 'Liberia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Libia', 'Libia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Liechtenstein', 'Liechtenstein');
INSERT INTO "DataManager_country"(name, forms) VALUES('Litwa', 'Litwa');
INSERT INTO "DataManager_country"(name, forms) VALUES('Luksemburg', 'Luksemburg');
INSERT INTO "DataManager_country"(name, forms) VALUES('Łotwa', 'Łotwa');
INSERT INTO "DataManager_country"(name, forms) VALUES('Macedonia', 'Macedonia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Madagaskar', 'Madagaskar');
INSERT INTO "DataManager_country"(name, forms) VALUES('Malawi', 'Malawi');
INSERT INTO "DataManager_country"(name, forms) VALUES('Malediwy', 'Malediwy');
INSERT INTO "DataManager_country"(name, forms) VALUES('Malezja', 'Malezja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Mali', 'Mali');
INSERT INTO "DataManager_country"(name, forms) VALUES('Malta', 'Malta');
INSERT INTO "DataManager_country"(name, forms) VALUES('Maroko', 'Maroko');
INSERT INTO "DataManager_country"(name, forms) VALUES('Mauretania', 'Mauretania');
INSERT INTO "DataManager_country"(name, forms) VALUES('Mauritius', 'Mauritius');
INSERT INTO "DataManager_country"(name, forms) VALUES('Meksyk', 'Meksyk');
INSERT INTO "DataManager_country"(name, forms) VALUES('Mikronezja', 'Mikronezja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Mjanma', 'Mjanma,Burma');
INSERT INTO "DataManager_country"(name, forms) VALUES('Mołdawia', 'Mołdawia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Monako', 'Monako');
INSERT INTO "DataManager_country"(name, forms) VALUES('Mongolia', 'Mongolia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Mozambik', 'Mozambik');
INSERT INTO "DataManager_country"(name, forms) VALUES('Mumbaj', 'Mumbaj,Bombaj');
INSERT INTO "DataManager_country"(name, forms) VALUES('Naddniestrze', 'Naddniestrze');
INSERT INTO "DataManager_country"(name, forms) VALUES('Namibia', 'Namibia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Nauru', 'Nauru');
INSERT INTO "DataManager_country"(name, forms) VALUES('Nepal', 'Nepal');
INSERT INTO "DataManager_country"(name, forms) VALUES('Niemcy', 'Niemcy');
INSERT INTO "DataManager_country"(name, forms) VALUES('Niger', 'Niger');
INSERT INTO "DataManager_country"(name, forms) VALUES('Nigeria', 'Nigeria');
INSERT INTO "DataManager_country"(name, forms) VALUES('Nikaragua', 'Nikaragua');
INSERT INTO "DataManager_country"(name, forms) VALUES('Norwegia', 'Norwegia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Nowa Zelandia', 'Nowa Zelandia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Oman', 'Oman');
INSERT INTO "DataManager_country"(name, forms) VALUES('Osetia Południowa', 'Osetia Południowa');
INSERT INTO "DataManager_country"(name, forms) VALUES('Pakistan', 'Pakistan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Panama', 'Panama');
INSERT INTO "DataManager_country"(name, forms) VALUES('Papua - Nowa Gwinea', 'Papua - Nowa Gwinea');
INSERT INTO "DataManager_country"(name, forms) VALUES('Paragwaj', 'Paragwaj');
INSERT INTO "DataManager_country"(name, forms) VALUES('Peru', 'Peru');
INSERT INTO "DataManager_country"(name, forms) VALUES('Polska', 'Polska');
INSERT INTO "DataManager_country"(name, forms) VALUES('Portugalia', 'Portugalia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Republika Południowej Afryki', 'Republika Południowej Afryki');
INSERT INTO "DataManager_country"(name, forms) VALUES('Republika Środkowoafrykańska', 'Republika Środkowoafrykańska');
INSERT INTO "DataManager_country"(name, forms) VALUES('Republika Zielonego Przylądka', 'Republika Zielonego Przylądka');
INSERT INTO "DataManager_country"(name, forms) VALUES('Rosja', 'Rosja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Rumunia', 'Rumunia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Rwanda', 'Rwanda');
INSERT INTO "DataManager_country"(name, forms) VALUES('Sahara Zachodnia', 'Sahara Zachodnia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Saint Kitts i Nevis', 'Saint Kitts i Nevis');
INSERT INTO "DataManager_country"(name, forms) VALUES('Saint Lucia', 'Saint Lucia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Saint Vincent i Grenadyny', 'Saint Vincent i Grenadyny');
INSERT INTO "DataManager_country"(name, forms) VALUES('Salwador', 'Salwador');
INSERT INTO "DataManager_country"(name, forms) VALUES('Samoa', 'Samoa');
INSERT INTO "DataManager_country"(name, forms) VALUES('San Marino', 'San Marino');
INSERT INTO "DataManager_country"(name, forms) VALUES('Senegal', 'Senegal');
INSERT INTO "DataManager_country"(name, forms) VALUES('Serbia', 'Serbia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Seszele', 'Seszele');
INSERT INTO "DataManager_country"(name, forms) VALUES('Sierra Leone', 'Sierra Leone');
INSERT INTO "DataManager_country"(name, forms) VALUES('Singapur', 'Singapur');
INSERT INTO "DataManager_country"(name, forms) VALUES('Słowacja', 'Słowacja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Słowenia', 'Słowenia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Somalia', 'Somalia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Somaliland', 'Somaliland');
INSERT INTO "DataManager_country"(name, forms) VALUES('Sri Lanka', 'Sri Lanka');
INSERT INTO "DataManager_country"(name, forms) VALUES('Stany Zjednoczone', 'Stany Zjednoczone,Ameryka,USA');
INSERT INTO "DataManager_country"(name, forms) VALUES('Suazi', 'Suazi');
INSERT INTO "DataManager_country"(name, forms) VALUES('Sudan', 'Sudan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Sudan Południowy', 'Sudan Południowy');
INSERT INTO "DataManager_country"(name, forms) VALUES('Surinam', 'Surinam');
INSERT INTO "DataManager_country"(name, forms) VALUES('Syria', 'Syria');
INSERT INTO "DataManager_country"(name, forms) VALUES('Szwajcaria', 'Szwajcaria');
INSERT INTO "DataManager_country"(name, forms) VALUES('Szwecja', 'Szwecja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Tadżykistan', 'Tadżykistan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Tajlandia', 'Tajlandia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Tajwan', 'Tajwan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Tanzania', 'Tanzania');
INSERT INTO "DataManager_country"(name, forms) VALUES('Timor Wschodni', 'Timor Wschodni');
INSERT INTO "DataManager_country"(name, forms) VALUES('Togo', 'Togo');
INSERT INTO "DataManager_country"(name, forms) VALUES('Tonga', 'Tonga');
INSERT INTO "DataManager_country"(name, forms) VALUES('Trynidad i Tobago', 'Trynidad i Tobago');
INSERT INTO "DataManager_country"(name, forms) VALUES('Tunezja', 'Tunezja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Turcja', 'Turcja');
INSERT INTO "DataManager_country"(name, forms) VALUES('Turkmenistan', 'Turkmenistan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Tuvalu', 'Tuvalu');
INSERT INTO "DataManager_country"(name, forms) VALUES('Uganda', 'Uganda');
INSERT INTO "DataManager_country"(name, forms) VALUES('Ukraina', 'Ukraina');
INSERT INTO "DataManager_country"(name, forms) VALUES('Urugwaj', 'Urugwaj');
INSERT INTO "DataManager_country"(name, forms) VALUES('Uzbekistan', 'Uzbekistan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Vanuatu', 'Vanuatu');
INSERT INTO "DataManager_country"(name, forms) VALUES('Watykan', 'Watykan');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wenezuela', 'Wenezuela');
INSERT INTO "DataManager_country"(name, forms) VALUES('Węgry', 'Węgry');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wielka Brytania', 'Wielka Brytania,Anglia,UK');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wietnam', 'Wietnam');
INSERT INTO "DataManager_country"(name, forms) VALUES('Włochy', 'Włochy');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wybrzeże Kości Słoniowej', 'Wybrzeże Kości Słoniowej');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspy Salomona', 'Wyspy Salomona');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspy Świętego Tomasza i Książęca', 'Wyspy Świętego Tomasza i Książęca');
INSERT INTO "DataManager_country"(name, forms) VALUES('Zambia', 'Zambia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Zimbabwe', 'Zimbabwe');
INSERT INTO "DataManager_country"(name, forms) VALUES('Zjednoczone Emiraty Arabskie', 'Zjednoczone Emiraty Arabskie');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspa Norfolk','Wyspa Norfolk');
INSERT INTO "DataManager_country"(name, forms) VALUES('Afryka Południowa','Afryka Południowa');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspa Bożego Narodzenia','Wyspa Bożego Narodzenia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Martynika','Martynika');
INSERT INTO "DataManager_country"(name, forms) VALUES('Portoryko','Portoryko');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspy Dziewicze','Wyspy Dziewicze');
INSERT INTO "DataManager_country"(name, forms) VALUES('Lebanon','Lebanon');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wake','Wake');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gwadelupa','Gwadelupa');
INSERT INTO "DataManager_country"(name, forms) VALUES('Hong Kong','Hong Kong');
INSERT INTO "DataManager_country"(name, forms) VALUES('Majotta','Majotta');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspa Man','Wyspa Man');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspy Cooka','Wyspy Cooka');
INSERT INTO "DataManager_country"(name, forms) VALUES('Niue','Niue');
INSERT INTO "DataManager_country"(name, forms) VALUES('Algeria','Algeria');
INSERT INTO "DataManager_country"(name, forms) VALUES('Comoros','Comoros');
INSERT INTO "DataManager_country"(name, forms) VALUES('Falklandy','Falklandy');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspy Marshalla','Wyspy Marshalla');
INSERT INTO "DataManager_country"(name, forms) VALUES('Saint Vincent and the Grenadines','Saint Vincent and the Grenadines');
INSERT INTO "DataManager_country"(name, forms) VALUES('Aruba','Aruba');
INSERT INTO "DataManager_country"(name, forms) VALUES('Makau','Makau');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gujana Francuska','Gujana Francuska');
INSERT INTO "DataManager_country"(name, forms) VALUES('Anguilla','Anguilla');
INSERT INTO "DataManager_country"(name, forms) VALUES('Polinezja Francuska','Polinezja Francuska');
INSERT INTO "DataManager_country"(name, forms) VALUES('Papua Nowa Gwinea','Papua Nowa Gwinea');
INSERT INTO "DataManager_country"(name, forms) VALUES('Jersey','Jersey');
INSERT INTO "DataManager_country"(name, forms) VALUES('West Bank','West Bank');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kongo (Brazzaville)','Kongo (Brazzaville)');
INSERT INTO "DataManager_country"(name, forms) VALUES('Saint Helena','Saint Helena');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wallis i Futuna','Wallis i Futuna');
INSERT INTO "DataManager_country"(name, forms) VALUES('Guernsey','Guernsey');
INSERT INTO "DataManager_country"(name, forms) VALUES('Johnston','Johnston');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gwinea-Bissau','Gwinea-Bissau');
INSERT INTO "DataManager_country"(name, forms) VALUES('Turks i Caicos','Turks i Caicos');
INSERT INTO "DataManager_country"(name, forms) VALUES('Antyle Holenderskie','Antyle Holenderskie');
INSERT INTO "DataManager_country"(name, forms) VALUES('Grenlandia','Grenlandia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Georgia Południowa i Sandwich Południowy','Georgia Południowa i Sandwich Południowy');
INSERT INTO "DataManager_country"(name, forms) VALUES('Midway','Midway');
INSERT INTO "DataManager_country"(name, forms) VALUES('Guam','Guam');
INSERT INTO "DataManager_country"(name, forms) VALUES('Bermudy','Bermudy');
INSERT INTO "DataManager_country"(name, forms) VALUES('Gibraltar','Gibraltar');
INSERT INTO "DataManager_country"(name, forms) VALUES('Suriname','Suriname');
INSERT INTO "DataManager_country"(name, forms) VALUES('Brytyjskie Wyspy Dziewicze','Brytyjskie Wyspy Dziewicze');
INSERT INTO "DataManager_country"(name, forms) VALUES('Antarktyda','Antarktyda');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kongo (Kinshasa)','Kongo (Kinshasa)');
INSERT INTO "DataManager_country"(name, forms) VALUES('Mariany Północne','Mariany Północne');
INSERT INTO "DataManager_country"(name, forms) VALUES('Saint-Pierre i Miquelon','Saint-Pierre i Miquelon');
INSERT INTO "DataManager_country"(name, forms) VALUES('Brytyjskie Terytorium Oceanu Indyjskiego','Brytyjskie Terytorium Oceanu Indyjskiego');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspy Kokosowe','Wyspy Kokosowe');
INSERT INTO "DataManager_country"(name, forms) VALUES('Palau','Palau');
INSERT INTO "DataManager_country"(name, forms) VALUES('Kajmany','Kajmany');
INSERT INTO "DataManager_country"(name, forms) VALUES('Samoa Amerykańskie','Samoa Amerykańskie');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspy Owcze','Wyspy Owcze');
INSERT INTO "DataManager_country"(name, forms) VALUES('Palestyna','Palestyna');
INSERT INTO "DataManager_country"(name, forms) VALUES('Reunion','Reunion');
INSERT INTO "DataManager_country"(name, forms) VALUES('Svalbard','Svalbard');
INSERT INTO "DataManager_country"(name, forms) VALUES('Nowa Kaledonia','Nowa Kaledonia');
INSERT INTO "DataManager_country"(name, forms) VALUES('Montserrat','Montserrat');
INSERT INTO "DataManager_country"(name, forms) VALUES('Wyspy Solomona','Wyspy Solomona');
